        !COMPILER-GENERATED INTERFACE MODULE: Sun May 21 19:49:23 2023
        MODULE EXECUTE__genmod
          INTERFACE 
            FUNCTION EXECUTE(PARAMS) RESULT(MESSAGE)
              CHARACTER(*) :: PARAMS
              CHARACTER(LEN=500) :: MESSAGE
            END FUNCTION EXECUTE
          END INTERFACE 
        END MODULE EXECUTE__genmod
