        !COMPILER-GENERATED INTERFACE MODULE: Sun Sep 17 12:15:39 2023
        MODULE MID2OPL2ENTERFILENAME__genmod
          INTERFACE 
            SUBROUTINE MID2OPL2ENTERFILENAME(DLG,ID,CALLBACKTYPE)
              REAL(KIND=4) :: DLG
              INTEGER(KIND=4) :: ID
              REAL(KIND=4) :: CALLBACKTYPE
            END SUBROUTINE MID2OPL2ENTERFILENAME
          END INTERFACE 
        END MODULE MID2OPL2ENTERFILENAME__genmod
