        !COMPILER-GENERATED INTERFACE MODULE: Sat Sep 30 11:38:59 2023
        MODULE MID2OPL2STARTCONVERSION__genmod
          INTERFACE 
            SUBROUTINE MID2OPL2STARTCONVERSION(DLG,ID,CALLBACKTYPE)
              REAL(KIND=4) :: DLG
              INTEGER(KIND=4) :: ID
              REAL(KIND=4) :: CALLBACKTYPE
            END SUBROUTINE MID2OPL2STARTCONVERSION
          END INTERFACE 
        END MODULE MID2OPL2STARTCONVERSION__genmod
