        !COMPILER-GENERATED INTERFACE MODULE: Sun Sep 17 12:15:39 2023
        MODULE MID2OPL2CONVERT__genmod
          INTERFACE 
            SUBROUTINE MID2OPL2CONVERT(DLG,ID,CALLBACKTYPE)
              USE FUNCTIONS
              TYPE (DIALOG) :: DLG
              INTEGER(KIND=4) :: ID
              INTEGER(KIND=4) :: CALLBACKTYPE
            END SUBROUTINE MID2OPL2CONVERT
          END INTERFACE 
        END MODULE MID2OPL2CONVERT__genmod
