        !COMPILER-GENERATED INTERFACE MODULE: Fri May 19 20:18:11 2023
        MODULE MID2OPL2APPLY__genmod
          INTERFACE 
            SUBROUTINE MID2OPL2APPLY(DLG,ID,CALLBACKTYPE)
              USE IFLOGM
              TYPE (DIALOG) :: DLG
              INTEGER(KIND=4) :: ID
              INTEGER(KIND=4) :: CALLBACKTYPE
            END SUBROUTINE MID2OPL2APPLY
          END INTERFACE 
        END MODULE MID2OPL2APPLY__genmod
