        !COMPILER-GENERATED INTERFACE MODULE: Fri Nov 03 14:15:44 2023
        MODULE MID2OPL2MIDILOAD__genmod
          INTERFACE 
            SUBROUTINE MID2OPL2MIDILOAD(DLG,ID,CALLBACKTYPE)
              USE FUNCTIONS
              TYPE (DIALOG) :: DLG
              INTEGER(KIND=4) :: ID
              INTEGER(KIND=4) :: CALLBACKTYPE
            END SUBROUTINE MID2OPL2MIDILOAD
          END INTERFACE 
        END MODULE MID2OPL2MIDILOAD__genmod
