        !COMPILER-GENERATED INTERFACE MODULE: Tue Oct 17 12:10:15 2023
        MODULE MID2OPL2CLOSE__genmod
          INTERFACE 
            SUBROUTINE MID2OPL2CLOSE(DLG,ID,CALLBACKTYPE)
              USE IFLOGM
              TYPE (DIALOG) :: DLG
              INTEGER(KIND=4) :: ID
              INTEGER(KIND=4) :: CALLBACKTYPE
            END SUBROUTINE MID2OPL2CLOSE
          END INTERFACE 
        END MODULE MID2OPL2CLOSE__genmod
