        !COMPILER-GENERATED INTERFACE MODULE: Sat Nov 04 20:18:56 2023
        MODULE MID2OPL2VGMPATH__genmod
          INTERFACE 
            SUBROUTINE MID2OPL2VGMPATH(DLG,ID,CALLBACKTYPE)
              USE FUNCTIONS
              TYPE (DIALOG) :: DLG
              INTEGER(KIND=4) :: ID
              INTEGER(KIND=4) :: CALLBACKTYPE
            END SUBROUTINE MID2OPL2VGMPATH
          END INTERFACE 
        END MODULE MID2OPL2VGMPATH__genmod
