        !COMPILER-GENERATED INTERFACE MODULE: Tue Oct 24 20:05:20 2023
        MODULE MID2OPL2CHANGEBANK__genmod
          INTERFACE 
            SUBROUTINE MID2OPL2CHANGEBANK(DLG,ID,CALLBACKTYPE)
              USE FUNCTIONS
              TYPE (DIALOG) :: DLG
              INTEGER(KIND=4) :: ID
              INTEGER(KIND=4) :: CALLBACKTYPE
            END SUBROUTINE MID2OPL2CHANGEBANK
          END INTERFACE 
        END MODULE MID2OPL2CHANGEBANK__genmod
