        !COMPILER-GENERATED INTERFACE MODULE: Fri May 19 20:07:00 2023
        MODULE MID2OPL2SUB__genmod
          INTERFACE 
            SUBROUTINE MID2OPL2SUB(DLG,ID,CALLBACKTYPE)
              USE IFLOGM
              TYPE (DIALOG) :: DLG
              INTEGER(KIND=4) :: ID
              INTEGER(KIND=4) :: CALLBACKTYPE
            END SUBROUTINE MID2OPL2SUB
          END INTERFACE 
        END MODULE MID2OPL2SUB__genmod
