        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 01 16:53:53 2023
        MODULE MID2OPL2CHANGESETTINGS__genmod
          INTERFACE 
            SUBROUTINE MID2OPL2CHANGESETTINGS(DLG,ID,CALLBACKTYPE)
              USE FUNCTIONS
              TYPE (DIALOG) :: DLG
              INTEGER(KIND=4) :: ID
              INTEGER(KIND=4) :: CALLBACKTYPE
            END SUBROUTINE MID2OPL2CHANGESETTINGS
          END INTERFACE 
        END MODULE MID2OPL2CHANGESETTINGS__genmod
