        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 20 20:09:02 2023
        MODULE MID2OPL2CHANGEBANK__genmod
          INTERFACE 
            SUBROUTINE MID2OPL2CHANGEBANK(DLG,ID,CALLBACKTYPE)
              USE FUNCTIONS
              TYPE (DIALOG) :: DLG
              INTEGER(KIND=4) :: ID
              INTEGER(KIND=4) :: CALLBACKTYPE
            END SUBROUTINE MID2OPL2CHANGEBANK
          END INTERFACE 
        END MODULE MID2OPL2CHANGEBANK__genmod
