        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 20 12:16:58 2023
        MODULE MID2OPL2BOXCHANGED__genmod
          INTERFACE 
            SUBROUTINE MID2OPL2BOXCHANGED(DLG,ID,CALLBACKTYPE)
              USE FUNCTIONS
              TYPE (DIALOG) :: DLG
              INTEGER(KIND=4) :: ID
              INTEGER(KIND=4) :: CALLBACKTYPE
            END SUBROUTINE MID2OPL2BOXCHANGED
          END INTERFACE 
        END MODULE MID2OPL2BOXCHANGED__genmod
