        !COMPILER-GENERATED INTERFACE MODULE: Sat May 20 14:14:59 2023
        MODULE MID2OPL2TEST__genmod
          INTERFACE 
            SUBROUTINE MID2OPL2TEST(DLG,ID,CALLBACKTYPE)
              USE MID2OPL2GLOBALS
              TYPE (DIALOG) :: DLG
              INTEGER(KIND=4) :: ID
              INTEGER(KIND=4) :: CALLBACKTYPE
            END SUBROUTINE MID2OPL2TEST
          END INTERFACE 
        END MODULE MID2OPL2TEST__genmod
