        !COMPILER-GENERATED INTERFACE MODULE: Sat Oct 28 15:05:19 2023
        MODULE WINMAIN__genmod
          INTERFACE 
            FUNCTION WINMAIN(HINSTANCE,HPREVINSTANCE,LPSZCMDLINE,       &
     &NCMDSHOW)
              INTEGER(KIND=4) :: HINSTANCE
              INTEGER(KIND=4) :: HPREVINSTANCE
              INTEGER(KIND=4) :: LPSZCMDLINE
              INTEGER(KIND=4) :: NCMDSHOW
              INTEGER(KIND=4) :: WINMAIN
            END FUNCTION WINMAIN
          END INTERFACE 
        END MODULE WINMAIN__genmod
